"""
Which Content assets does the game actually use? Run headless:

    UnrealEditor-Cmd.exe ActionRPG.uproject -run=pythonscript -script=Tools/audit_content.py -unattended -nullrhi

Starts from everything the C++ and game-data.json load by name (ROOTS below, plus all of /Game/RPG), follows
every hard and soft dependency in the asset registry, and writes Saved/content_audit.txt (used and unused
packages) and Content/.gitignore, which keeps the unused template assets on disk but out of git (they would only
cost Git LFS space). Keep ROOTS in step with the /Game/ paths in Source/, then rerun this after adding a use of
a template asset, and `git add` the asset.

Git holds what the default HD-2D look needs. Starter Content materials that HD-2D swaps for pixel art
(world3d.looks2d.pixelMaterials) only show in the 3D look, and their 4K textures are most of the weight, so they
stay local too: on a fresh clone the 3D look falls back to plain grey (add Starter Content to get them back).
"""
import json
import os
import unreal

STARTER_MATS = ["M_Brick_Clay_Old", "M_Brick_Cut_Stone", "M_Brick_Hewn_Stone", "M_CobbleStone_Pebble",
                "M_CobbleStone_Rough", "M_Concrete_Poured", "M_Ground_Grass", "M_Ground_Gravel",
                "M_Metal_Burnished_Steel", "M_Metal_Chrome", "M_Metal_Copper", "M_Metal_Gold", "M_Metal_Steel",
                "M_Rock_Slate", "M_Water_Lake", "M_Wood_Floor_Walnut_Worn", "M_Wood_Oak", "M_Wood_Walnut"]
with open(os.path.join(unreal.Paths.project_content_dir(), "Data", "game-data.json"), encoding="utf-8") as f:
    PIXEL_SWAPPED = set(json.load(f)["world3d"]["looks2d"]["pixelMaterials"])
STARTER_MATS = [m for m in STARTER_MATS if m not in PIXEL_SWAPPED]
DEATHS = ["MM_Death_Front_01", "MM_Death_Front_02", "MM_Death_Back_01", "MM_Death_Left_01", "MM_Death_Right_01"]

ROOTS = (["/Game/StarterContent/Materials/" + m for m in STARTER_MATS]
         + ["/Game/Characters/Mannequins/Anims/Death/" + d for d in DEATHS]
         + ["/Game/StarterContent/Props/SM_Bush", "/Game/StarterContent/Props/SM_Rock",
            "/Game/StarterContent/Particles/P_Smoke", "/Game/StarterContent/Particles/P_Fire",
            "/Game/StarterContent/Audio/Starter_Birds01", "/Game/StarterContent/Audio/Fire01_Cue",
            "/Game/Variant_Combat/VFX/NS_Damage", "/Game/Variant_Combat/Anims/AM_ComboAttack",
            "/Game/Variant_Combat/Anims/AM_ChargedAttack", "/Game/Variant_Combat/Anims/ABP_Manny_Combat",
            "/Game/Characters/Mannequins/Meshes/SKM_Quinn_Simple", "/Game/Characters/Mannequins/Meshes/SKM_Manny_Simple",
            "/Game/Characters/Mannequins/Materials/Manny/MI_Manny_01_New",
            "/Game/Characters/Mannequins/Materials/Manny/MI_Manny_02_New",
            "/Game/Characters/Mannequins/Anims/Unarmed/Jump/MM_Dash"])

reg = unreal.AssetRegistryHelpers.get_asset_registry()
reg.search_all_assets(True)
opts = unreal.AssetRegistryDependencyOptions(include_soft_package_references=True, include_hard_package_references=True,
                                             include_searchable_names=False, include_soft_management_references=True,
                                             include_hard_management_references=True)

all_pkgs = sorted({str(a.package_name) for a in reg.get_assets_by_path("/Game", recursive=True)})
roots = [p for p in all_pkgs if p.startswith("/Game/RPG/")] + ROOTS
missing = [r for r in ROOTS if r not in all_pkgs]

used, todo = set(), list(roots)
while todo:
    p = todo.pop()
    if p in used or not p.startswith("/Game/"):
        continue
    used.add(p)
    todo.extend(str(d) for d in (reg.get_dependencies(p, opts) or []))

content = unreal.Paths.project_content_dir()
def size(pkg):
    base = os.path.join(content, pkg[len("/Game/"):])
    return sum(os.path.getsize(base + e) for e in (".uasset", ".umap", ".uexp", ".ubulk") if os.path.exists(base + e))

unused = [p for p in all_pkgs if p not in used]
out = os.path.join(unreal.Paths.project_saved_dir(), "content_audit.txt")
with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("MISSING ROOTS %d\n" % len(missing))
    f.writelines("  %s\n" % m for m in missing)
    f.write("USED %d packages, %.1f MB\n" % (len(used), sum(size(p) for p in used if p in all_pkgs) / 1e6))
    f.writelines("  %s\n" % p for p in sorted(used))
    f.write("UNUSED %d packages, %.1f MB\n" % (len(unused), sum(size(p) for p in unused) / 1e6))
    f.writelines("  %s\t%d\n" % (p, size(p)) for p in unused)
unreal.log("[RPG] content audit -> " + out)

ignore = os.path.join(content, ".gitignore")
with open(ignore, "w", encoding="utf-8", newline="\n") as f:
    f.write("# Template assets nothing in the game uses: kept on disk, not in git. Generated by Tools/audit_content.py.\n")
    f.writelines("/%s.*\n" % p[len("/Game/"):] for p in unused)
unreal.log("[RPG] wrote " + ignore)
